package it.polimi.softeng.is25am10.model.cards;

import it.polimi.softeng.is25am10.model.boards.Coordinate;
import it.polimi.softeng.is25am10.model.boards.GoodsBoard;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Thi class contain the output generated by the cards.
 * It contains all the possible data about the effects
 * of a card.
 */
public class CardOutput implements Serializable {
    /**
     * Rewarded cash to the player.
     */
    public Map<String, Integer> cash = new HashMap<>();

    /**
     * The crew members killed by epidemic.
     */
    public Map<String, List<Coordinate>> killedCrew = new HashMap<>();

    /**
     * Removed tiles by an asteroid.
     */
    public Map<String, Coordinate> removed = new HashMap<>();

    /**
     * Rewarded items to player
     */
    public Map<String, List<GoodsBoard.Type>> rewards = new HashMap<>();
}